version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/ssl:/usr/share/nginx/ssl
  app:
    image: andersoncruzz/ssfer:1.0.2
    ports:
     - "443:5000"
    volumes:
     - ./models:/home/app/SSFER/models
